name: Azure storage account deployment with ARM template 1

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '.github/**'

env:
  AZURE_RG: RG-GH-STO-DEV
  AZURE_LOCATION: westeurope
  
jobs:
  deploy:
    name: Deploy ARM template to Azure
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@master
      
      - name: Login Azure
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL }}
          
      - name: Resource Group creation
        uses: azure/CLI@v1
        with:
          azcliversion: 2.35.0
          inlineScript: |
            az group create --name ${{ env.AZURE_RG }} --location ${{ env.AZURE_LOCATION }}
          
      - name: Deploy ARM Template
        id: deployarm
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBID }}
          resourceGroupName: ${{ env.AZURE_RG }}
          template: ./azuredeploy.json
          parameters: ./azuredeploy.parameters.json
          deploymentName: GHADeploy-01
          deploymentMode: Incremental
          
      - name: Display storage account name
        run: echo $${{ steps.deployarm.outputs.storageAccountName }} 
